### PR TITLE
Allow custom dropping of tabs inside other tabs

### LINKED ISSUE #254: Dragging and dropping tabs within/into/out of a panel
I'm trying to make a panel where you can drag and drop to reorder things inside, but you can also drag something outside of the panel to create a new tab. I want to use FlexLayout's existing drag and drop system for this. Is there an existing way to allow dropping this custom "new tab" _inside_ of my panel?

Like for example, you can drag things between tabs in tab bars:

image

Is there a way to support this somehow for objects inside my my panel?

### PR DESCRIPTION
**Pull request by LoganDark**
This allows consumers to use flexlayout's dnd infrastructure for
the pretty outline and ability to drag it out to dock with other
tabs, while also being able to interact more deeply with the
components inside of tabs.

Example: a list where each item can be dragged around in the same
list, or dragged out to create a new tab. Tabs can also be dragged
from outside, into the list! This kind of interaction is currently
not possible with flexlayout.

This new feature only requires one new prop passed to the layout.
A user-provided function will tell flexlayout when it wants to
override the default docking behavior. Currently, only tabs can
have their drop behavior modified. I don't think tab strips need
it.

Closes #254

I couldn't find a fitting demo other than overriding drag for something. Please advise if you need the behavior changed. Alternatively you have access to the branch.

### CODE REVIEW

**Comment by LoganDark** [comment]
By the way, your dragging system is very good. I really like your DropInfo, but unfortunately it could not be reused for this case. I think the solution I settled on is adequate.

**Comment by LoganDark** [comment]
https://user-images.githubusercontent.com/4723091/135400331-81b26b20-5343-46fa-8aab-08a8fd57cc68.mp4

Here's a video where the wikipedia tab snaps the drag into a 50x50 grid, and then logs a message when a tab is dropped. Since the callback does nothing else, the tab does not move when dropped on wikipedia. This is what the demo does

**Comment by LoganDark** [comment]
Also note that this is can be potentially explosive when mixed with popouts, if the popout tabs rely on the drag and drop system, because dragging and dropping won't work properly within the popped out tab. But that's too complex to solve reasonably

**Comment by LoganDark** [comment]
I found a bug, tabs inside borders aren't treated properly. Converting this PR to draft until I fix it

**Comment by LoganDark** [comment]
https://user-images.githubusercontent.com/4723091/135442571-484d685b-1491-417e-9e28-4168ce4d9624.mp4

**Comment by LoganDark** [comment]
@nealus please review. waiting on this feature

**Comment by nealus** [comment]
Thanks for this, looks good, I can see a potential problem with id's in the demo, but I can fix that once it's merged

**Comment by LoganDark** [comment]
> potential problem with id's in the demo

It is very much a problem, can't really be solved without assigning new ids automatically. Wasn't sure how/when to do that.

Thanks for merge!

**Comment by LoganDark** [comment]
By the way @nealus, the example uses private/internal API to convert TabNodes to JSON. Perhaps it's time to make that method public. I can make a PR for it

**Comment by nealus** [comment]
yes that would be good, thanks

**Pull request merged**
