### PR TITLE
Add docs for active tabset attribute

### PR DESCRIPTION
**Pull request by acontreras89**
Document the `active` attribute for tabsets.

### CODE REVIEW

**Comment by nealus** [comment]
active is not actually an attribute of the tabset, like the others, there is a isActive() method but it cannot be set in json as an attribute

**Comment by acontreras89** [comment]
@nealus yes it is (can be seen [here](https://github.com/caplin/FlexLayout/blob/ded148d4523d66742c0504efcecdc0b4ff9d97c4/examples/demo/layouts/sub.layout#L108) and [here](https://github.com/caplin/FlexLayout/blob/ded148d4523d66742c0504efcecdc0b4ff9d97c4/examples/demo/layouts/sub.layout#L48)), and the fact that it is not documented causes some confusion when starting to use the library (see [my comment](https://github.com/caplin/FlexLayout/issues/51#issuecomment-1658585597) in issue #51).

When instantiating a layout, you either pass the `active` flag to some of the tabsets in your model or you will not be able to use `addTabToActiveTabSet` until the user actually focuses one of them, which is quite annoying and a completely silent no-op.

**Comment by nealus** [comment]
yes ok, you can specify it in the initial json layout, but you set the active tabset on the model (you cannot update the active attribute of a tabset, it is not actually a tabset attribute like others), can you add a note that effect, the I will merge your change.

**Comment by acontreras89** [comment]
@nealus note added 👍 hope this is ok

**Review by nealus — APPROVED** [review]

**Pull request merged**
