### PR TITLE
Allow custom drops to know when they are invalidated

### PR DESCRIPTION
**Pull request by LoganDark**
Use case: You want people to be able to scroll the list while they are dragging an item in it

Depends on #266 

https://user-images.githubusercontent.com/4723091/136687188-f6dca673-e876-4293-adb2-f5ed2a22c16f.mp4

~~Currently the outline is not updated on scroll, I want to come up with a solution for that too. Stay tuned and I will add it to this PR~~ Fixed

### CODE REVIEW

**Comment by nealus** [comment]
After I drag a few new tabs into the list (using the Add Drag button) I cannot drag the bottom tab up correctly

**Comment by nealus** [comment]
I expect it's due to:
react.development.js:220 Warning: Each child in a list should have a unique "key" prop.

**Comment by LoganDark** [comment]
> I expect it's due to: react.development.js:220 Warning: Each child in a list should have a unique "key" prop.

I knew this the moment you said it

**Comment by nealus** [comment]
Still get the problem after adding a few tabs with Add drag, no error when adding but if you reload the page and goto NewFeatures then you get the unique key warning again

**Comment by LoganDark** [comment]
> Still get the problem after adding a few tabs with Add drag, no error when adding but if you reload the page and goto NewFeatures then you get the unique key warning again

Make sure you reload from file so that the tabs without keys aren't present anymore

**Comment by nealus** [comment]
```
						"config": {
							"storedTabs": [
								{
									"id": "#6d672c81-c81f-46a9-9ca7-ee16ecf451ee",
									"component": "grid",
									"name": "Grid 1"
								},
								{
									"component": "grid",
									"name": "Grid 4"
								},
								{
									"component": "grid",
									"name": "Grid 3"
								},
								{
									"component": "grid",
									"name": "Grid 2"
								}
							]
```

**Comment by nealus** [comment]
debugging on:
```
    const kickstartingCallback = useCallback((dragging: TabNode | IJsonTabNode) => {
        const json = dragging instanceof TabNode ? dragging.toJson() as IJsonTabNode : { id: '#' + v4(), ...dragging }
```
it only goes thru that line for the first tab addition!

**Comment by LoganDark** [comment]
> debugging on:
> 
> ```
>     const kickstartingCallback = useCallback((dragging: TabNode | IJsonTabNode) => {
>         const json = dragging instanceof TabNode ? dragging.toJson() as IJsonTabNode : { id: '#' + v4(), ...dragging }
> ```
> 
> it only goes thru that line for the first tab addition!

Already fixed that, now need to fix the method

**Comment by LoganDark** [comment]
The code is duplicated so maybe it should be in a utility function somewhere

**Comment by LoganDark** [comment]
This is the last of my PRs for now, so please consider publishing a new release :)

**Pull request merged**
