### PR TITLE
Add eslint & Add a example created by create-react-app using yarn workspace

### PR DESCRIPTION
**Pull request by arnoldcui**
TSLint is deprecated. see [tslint](https://github.com/palantir/tslint) 
Use eslint instead.

image

### CODE REVIEW

**Comment by arnoldcui** [comment]
And I have add a example create by create-react-app by using yarn workspace.It will be much easier to debug Flexlayout.
You can check the code at [arnold's Change](https://github.com/arnoldcui/FlexLayout)

**Comment by arnoldcui** [comment]
With yarn workspace & yarn link. We can easily start a test example.

**Comment by arnoldcui** [comment]
use editorconfig to define 

indent_style = space
indent_size = 4

**Comment by nealus** [comment]
looks good, thanks for this pr

**Pull request merged**
